# CircleCI configuration
version: 2.1

# Slack notification orb
orbs:
  slack: circleci/slack@4.4.2

# # CircleCi commands
# commands:


# Circleci jobs
jobs:
  lint-check:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: lint dockerfile using hadolint
          command: |
            sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.5.0/hadolint-Linux-x86_64
            sudo chmod +x /bin/hadolint
            hadolint Dockerfile

      - run:
          name: lint app using npm
          command: |
            cd app
            npm run lint

  # volnubility-check:
  #   docker:
  #     - image: circleci/node:13.8.0
  #   steps:


 
  # build-docker:



  # push-docker:



  # deploy-infrastructure:


  
# Circleci workflow
workflows:
  default:
    jobs:
      - lint-check
