# CircleCI configuration
version: 2.1

# Slack notification orb
orbs:
  slack: circleci/slack@4.4.2

# # CircleCi commands
# commands:


# Circleci jobs
jobs:
  app-build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: build application
          command: |
            cd app
            npm install 
            npm run build
      - save_cache:
          paths: [app/node_modules]
          key: app-build


  lint-check:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [app-build]
      - run:
          name: lint dockerfile using hadolint
          command: |
            sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.5.0/hadolint-Linux-x86_64
            sudo chmod +x /bin/hadolint
            hadolint Dockerfile
      - run:
          name: lint app using npm
          command: |
            cd app
            npm install
            npm run lint
      - save_cache:
          paths: [app/node_modules]
          key: app-build


  vulnerability-check:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [app-build]
      - run:
          name: vulnerability check on node packages
          command: |
            cd app
            npm install
            npm audit fix
      - save_cache:
          paths: [app/modules]
          key: app-build
  

  docker-push:
    docker: 
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: docker install
          command: |
            yum update -y 
            amazon-linux-extras install docker -y
            docker --version
      - run:
          name: docker image push to ECR
          command: |
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 669700445040.dkr.ecr.us-east-1.amazonaws.com
            ./run_docker.sh
            docker tag udacity-capstone-bcrypt:latest 669700445040.dkr.ecr.us-east-1.amazonaws.com/udacity-capstone-bcrypt:latest
            docker push 669700445040.dkr.ecr.us-east-1.amazonaws.com/udacity-capstone-bcrypt:latest

      



 
  # build-docker:



  # push-docker:



  # deploy-infrastructure:


  
# Circleci workflow
workflows:
  default:
    jobs:
      - app-build
      - lint-check:
          requires: [app-build]
      - vulnerability-check:
          requires: [app-build]
      - docker-push:
          requires: [lint-check, vulnerability-check]
