apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: EKS-bcrypt-cluster
  region: us-east-1
  version: 1.16

vpc:
  id: vpc-04fd177fb778820de
  cidr: "192.168.0.0/16"
  subnets:
    public:
      us-east-1a:
        id: subnet-0d1ac1232cf8e99b0
      us-east-1b:
        id: subnet-0462409ee9c771837
    private:
      us-east-1a:
        id: subnet-0c8442559985248c2
      us-east-1b:
        id: subnet-03e6153f027e7e904

nodeGroups:
  - name: EKS-public-workers
    instanceType: t2.medium
    desiredCapacity: 2
  - name: EKS-private-workers
    instanceType: t2.medium
    desiredCapacity: 1
    privateNetworking: true